

# --SITE SETTINGS--
title: "Red White and Black"
email: dchildress@library.ucla.edu
description:
baseurl: "/demostite" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_repo: https://github.com/kirschbombe/flaneur
copyright_statement: © 2017 Dawn Childress. CC BY-NC-SA 4.0.

# build settings
markdown: kramdown
encoding: utf-8

# --STYLES--
accent_color: rgb(204, 0, 1)  # accent color can be any css accepted value
accent_font: 'Univers bold' 
base_font: 'Univers light'
  
# --MAP SETTINGS--
mapsettings:
  map-tileset: 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
  map-credits: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  minZoom: 0
  maxZoom: 19
  setView: '[35.794910, -78.699867], 13'  # set map center point and zoom. See http://leafletjs.com/reference-1.2.0.html for more info.
  marker-grouping: single # sets the default clustering action. Options: grouped, single
  directionapi: https://router.project-osrm.org/route/v1/walking/

# Truncates map marker popup on small screens to only display post title
window-height: 600
window-width: 550

# --LINKS--
collections:
  posts:
    output: true
    permalink: /article/:name
  article-index:
    output: true
    permalink: /article-index/:name/

permalink: /:categories/:title/

# --MENU--
menu-type: dropdown  # options: dropdown, circle

# settings for circle menu
menu-height: '200px'
menu-width: '200px'
menu-opacity: '.95'
